# Generated by Django 3.2.6 on 2021-09-22 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('fullname', models.CharField(max_length=50)),
                ('staffid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('college', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('is_student', models.BooleanField(default=False, editable=False)),
                ('is_staff', models.BooleanField(default=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('fullname', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('college', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=1)),
                ('section', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('is_student', models.BooleanField(default=True, editable=False)),
                ('is_staff', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bonafide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_request', models.CharField(max_length=200)),
                ('date_of_request', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('dealt_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.staff')),
                ('student_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
            ],
        ),
    ]
