# Generated by Django 3.2.6 on 2021-09-22 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonafide',
            name='date_of_approval',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
