# Generated by Django 3.2.6 on 2021-09-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_bonafide_date_of_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafide',
            name='dealt_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.staff'),
        ),
    ]
