# Generated by Django 3.2.6 on 2021-09-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_alter_bonafide_dealt_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonafide',
            old_name='date_of_approval',
            new_name='date_handled',
        ),
    ]
