# Generated by Django 3.2.6 on 2021-09-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_alter_bonafide_date_handled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafide',
            name='date_handled',
            field=models.DateField(default=None, null=True),
        ),
    ]
