# Generated by Django 3.2.7 on 2021-10-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_alter_bonafide_date_handled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='bonafide',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
