# Generated by Django 3.2.7 on 2021-10-11 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0009_alter_bonafide_date_of_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonafide',
            name='accommodation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bonafide',
            name='batch',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bonafide',
            name='quota',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bonafide',
            name='date_of_request',
            field=models.DateField(default=datetime.date(2021, 10, 11)),
        ),
    ]
