# Generated by Django 3.2.7 on 2021-10-18 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_auto_20211011_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafide',
            name='date_of_request',
            field=models.DateField(default=datetime.date(2021, 10, 18)),
        ),
    ]
