# Generated by Django 3.2.7 on 2021-10-19 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_alter_bonafide_date_of_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='karthikeyansvkm23@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bonafide',
            name='date_of_request',
            field=models.DateField(default=datetime.date(2021, 10, 19)),
        ),
    ]
