# Generated by Django 3.2.7 on 2021-10-19 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_auto_20211019_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafide',
            name='date_of_request',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
