# Generated by Django 3.2.7 on 2021-10-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0013_alter_bonafide_date_of_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20)),
                ('staff_id', models.CharField(max_length=50)),
            ],
        ),
    ]
