# Generated by Django 3.2.7 on 2021-10-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0014_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='Not Allocated', max_length=50),
        ),
    ]
