# Generated by Django 3.2.7 on 2021-10-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0015_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(default='Not Allocated', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
