# Generated by Django 3.2.7 on 2021-10-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0016_auto_20211020_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_fullform',
            field=models.CharField(default='Computer Science and Engineering', max_length=100),
            preserve_default=False,
        ),
    ]
