# Generated by Django 3.2.7 on 2021-10-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0017_department_department_fullform'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonafide',
            name='first_graduate',
            field=models.CharField(default='No', max_length=20),
            preserve_default=False,
        ),
    ]
